### PR TITLE
Update to .NET 7

### PR DESCRIPTION
**Pull request by thiagomoises**
Project Upgrade to .NET7

PR about #117

### CODE REVIEW

**Review by Removable — APPROVED** [review]

**Comment by ekjuanrejon** [comment]
Why this has not been merged?

**Comment by skoruba** [comment]
Will be merged, thx

**Comment by ekjuanrejon** [comment]
any progress on this pr?

**Comment by skoruba** [comment]
I will merge it soon, I am sorry for delay. 👍

**Comment by motuzko** [comment]
...and?

**Comment by ekjuanrejon** [comment]
and there is 
https://github.com/openiddict/openiddict-core
https://github.com/keycloak/keycloak
etc..

**Comment by skoruba** [comment]
Hi guys, I am sorry for long delay, I was busy. I will update to .NET 7 and the last version of Duende IS next week.
Thanks!

**Comment by thiagomoises** [comment]
> and there is https://github.com/openiddict/openiddict-core https://github.com/keycloak/keycloak etc..

This isn't a good comment. PR must been about the change. This comment don't contributed with nothing
If you wanna sugest other application option to the guys, use the issue to this!

**Comment by thiagomoises** [comment]
> Hi guys, I am sorry for long delay, I was busy. I will update to .NET 7 and the last version of Duende IS next week. Thanks!

I understand
But, how a lot of time as passed, can we update to .NET8 now?
I think that looks like a good idea, 'case apparentely  have not braking changes between .NET7 and .NET8

**Comment by skoruba** [comment]
I updated to .NET 8 - #192.
Thank you and I am sorry for delay.

**Pull request closed without merging**
