### PR TITLE
switch base dotnet images from buster-slim to alpine

### PR DESCRIPTION
**Pull request by FabienDehopre**
I think using Alpine based images instead of the default buster-slim images for docker is a good idea to reduce the size of the download and reduce the storage needed.

### CODE REVIEW

**Comment by skoruba** [comment]
Good idea, I am using the default images which were generated via VS. 😊

**Comment by epoyraz** [comment]
Bear in mind: Alpine uses **musl** libc instead of **glibc**.
It can have some performance impact (which might not be a concern in this case)
https://superuser.com/questions/1219609/why-is-the-alpine-docker-image-over-50-slower-than-the-ubuntu-image

**Comment by FabienDehopre** [comment]
I don't know if it would be a real issue in small to medium size projects. Maybe on bigger projects that should handle lot of request/response at the same time. 
Maybe only the STS project should remain on the default image for performance reason but for the API and Admin, I don't think it would change a lot.
Let me know if you need me to change something (e.g.: roll back the STS Dockerfile). Or the PR can just be abandoned. This is not a big change anyway.

**Comment by Aloento** [comment]
`Only the invariant culture is supported in globalization-invariant mode` will happened because aspnet-alpine don't have ICU.
You need install it by your self.

**Pull request closed without merging**
